
development:
  adapter: mysql2
#  adapter: mysql
  database: xplain_development
  username: root
  password: inguanZ0FT
  socket: /tmp/mysql.sock #mac
#  adapter: mysql
#  database: actomosc_menucook
#  username: actomosc_root
#  password: juli4nM4ri4n4~
#  socket: /tmp/mysql.sock #mac
#  socket: /var/run/mysqld/mysqld.sock   #Linux

test:
  adapter: mysql2
  database: menucook_test
  username: root
  password: inguanZ0FT
  socket: /tmp/mysql.sock #mac
#  socket: /var/run/mysqld/mysqld.sock   #Linux

production:
  adapter: mysql2
  database: xplain
  username: production
  password: juli4nM4ri4n4~
#  socket: /tmp/mysql.sock #mac
  socket: /var/run/mysqld/mysqld.sock   #Linux
#  socket: /var/lib/mysql/mysql.sock
#  socket: /tmp/mysql.sock   #hm
